[package]
name = "face_cropper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = "0.25.9"
rustface = "0.1.7"
anyhow = "1.0.100"
tempfile = "3.23.0"
